### ISSUE TITLE
Major Bug: Game Flickers alot

### ISSUE THREAD

**Issue by hYdos** [Blaze4D-MC/Blaze4D#27]
Current speculated causes:

- Shaders and Textures are not being applied to the right objects, causing misalignment.
- Padding is not implemented so more misalignment in the big vertex buffer may happen

I currently have no clue on a good way to implement padding as Minecraft sometimes has 1 byte of padding or 4 bytes (a float) worth of padding.

Whichever contributor wants to work on the Padding thing, please assign themselves.

@burgerguy can you please look into the textures and shaders issue before anything else? its quite important for making progress.

**Comment by burgerguy** [comment]
When I get the chance I'm down to fix the padding thing and make the VertexFormatElements even more dynamic. I'm also going to fix the predefined vertex format list as that provides a major speedup over creating a new one and checking the map.

**Comment by burgerguy** [comment]
this is now mostly fixed, we are back to a pre-big_nuts state

**Comment by burgerguy** [comment]
this has been fixed in the latest commit. we may want to adopt a better way of doing this, but for now, this is what we got.
