### ISSUE TITLE
fix not being to compile mod

### ISSUE THREAD

**Issue by teh404guy** [Blaze4D-MC/Blaze4D#38]
> Configure project :
Fabric Loom: 0.9.25
Using project based jar storage

> Task :Rosella:compileKotlin
w: /home/censored/Documents/CompileStuff/Blaze4D/Rosella/src/main/kotlin/me/hydos/rosella/render/Vk.kt: (133, 39): 'vkQueueWaitIdle(): Int' is deprecated. Deprecated in Java
w: /home/censored/Documents/CompileStuff/Blaze4D/Rosella/src/main/kotlin/me/hydos/rosella/render/model/ModelLoader.kt: (56, 29): Parameter 'scene' is never used

> Task :Rosella:compileJava
Note: /home/censored/Documents/CompileStuff/Blaze4D/Rosella/src/main/java/me/hydos/rosella/memory/Memory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: release version 16 not supported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
6 actionable tasks: 6 executed

**Comment by IMS212** [comment]
no lol

**Comment by teh404guy** [comment]
ok

**Comment by teh404guy** [comment]
looks like stupid me forgot to install adoptopenjdk fully and not just the jre
