### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by arceuss** [Blaze4D-MC/Blaze4D#4]
[latest.log](https://github.com/hYdos/Blaze4D/files/6758998/latest.log)
on latest workflow artifact

**Comment by hYdos** [comment]
this bug is caused because i dont shadow my vulkan engine into the mod's jar. ill fix it in 1-2 days,

**Comment by SirObby** [comment]
@hYdos or 3 days right?

**Comment by hYdos** [comment]
> @hYdos or 3 days right?

gradle is being a pain

**Comment by SirObby** [comment]
Has this problem been fixed yet?

**Comment by hYdos** [comment]
not yet

**Comment by hYdos** [comment]
@ramidzkh can you work on this?
